<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!-- Consider adding an manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en" itemscope itemtype="http://schema.org/Product"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <!-- Use the .htaccess and remove these lines to avoid edge case issues.
       More info: h5bp.com/b/378 -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>Blog \ <?= $this->title; ?></title>
  <meta name="description" content="" />
  <meta name="keywords" content="" />
  <meta name="author" content="humans.txt">

  <link rel="shortcut icon" href="favicon.png" type="image/x-icon" />

  <!--Facebook Metadata /-->
  <meta property="fb:page_id" content="" />
    <meta property="og:image" content="" />
    <meta property="og:description" content=""/>
    <meta property="og:title" content=""/>

  <!--Google+ Metadata /-->
    <meta itemprop="name" content="">
    <meta itemprop="description" content="">
    <meta itemprop="image" content="">

  <!-- Mobile viewport optimized: j.mp/bplateviewport -->
  <meta name="viewport" content="width=device-width,initial-scale=1">

  <!-- Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons -->

  <!-- CSS: implied media=all -->
  <!-- CSS concatenated and minified via ant build script-->
  <!-- <link rel="stylesheet" href="css/minified.css"> -->

  <!-- CSS imports non-minified for staging, minify before moving to production-->
  <link rel="stylesheet" href="/css/bootstrap.min.css">
  <!-- end CSS-->

  <style type="text/css">
    body { padding-top: 70px; }
    h3 a { color: #006bAd; }
    h3 a:hover, h3:visited { text-decoration: none; }
    .article-container { border: 1px solid #DDD; border-radius: 4px; padding: 8px; }
    .sqlqueries { margin-top: 40px; }
  </style>
  <!-- All JavaScript at the bottom, except for Modernizr / Respond.
       Modernizr enables HTML5 elements & feature detects; Respond is a polyfill for min/max-width CSS3 Media Queries
       For optimal performance, use a custom Modernizr build: www.modernizr.com/download/ -->
  <script src="/js/libs/modernizr-2.0.6.min.js"></script>
</head>

<body data-spy="scroll" data-offset="50">
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="brand" href="/">Blog</a>
        <div class="nav-collapse">
          <ul id="mainNav" class="nav">
            <li><a href="/">Home</a></li>
            <li><a href="/categories/view/1">Graphisme</a></li>
            <li><a href="/categories/view/2">Photographies</a></li>
            <li><a href="/categories/view/3">Peintures</a></li>
          </ul>
          <ul class="nav pull-right">
            <?php if(\Bloom\Auth\Auth::isLogged()): ?>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="/admin/articles">Articles</a></li>
                <li class="divider"></li>
                <li><a href="/users/signout">Sign Out</a></li>
              </ul>
            </li>
            <?php else: ?>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sign In <b class="caret"></b></a>
              <ul class="dropdown-menu" style="padding: 0;">
                <li>
                  <form method="post" action="/users/signin"style="margin-bottom: 0;" class="well">
                    <input name="email" type="text" class="span3" placeholder="Email">
                    <input name="password" type="password" class="span3" placeholder="Password">
                    <button href="#" class="btn btn-primary" style="color: #fff; margin: 0;">Sign In</button>
                  </form>
                </li>
              </ul>
            </li>
            <?php endif; ?>
          </ul>
        </div><!-- /.nav-collapse -->
      </div>
    </div><!-- /navbar-inner -->
  </div><!-- /navbar -->
  <div class="container">
    <header></header>
    <?= $this->flashMessages; ?>
    <?= $this->content ?>
    <?php if(\Bloom\Config::get("application")['debug'] === true): ?>
    <div class="sqlqueries">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>SQL Queries</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
          <?php foreach ($this->stack as $value): ?>
              <pre><?= $value; ?></pre>
          <?php endforeach; ?>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <?php endif; ?>
    <footer></footer>
  </div> <!--! end of #container -->

  <div class="modal fade" id="signInModal">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">×</button>
      <h3>Sign In</h3>
    </div>
    <div class="modal-body">
      <form class="form-inline">
        <input type="text" class="span3" placeholder="Email">
        <input type="password" class="span3" placeholder="Password">
      </form>
    </div>
    <div class="modal-footer">
      <a href="#" class="btn" data-dismiss="modal">Close</a>
      <a href="#" class="btn btn-primary">Sign In</a>
    </div>
  </div>

  <!-- JavaScript at the bottom for fast page loading -->

  <!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline -->
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="/js/libs/jquery-1.7.2.min.js"><\/script>')</script>

  <script src="/js/bootstrap.min.js"></script>
  <!-- end scripts-->

  <script type="text/javascript">
    $(function(){
      $("#mainNav").find("a[href$='"+ window.location.pathname +"']").parent().addClass("active");
      $("a.delete").on("click", function(e) {
        alert("I'm gonna delete that article, are you sure ?");
      });
    });
  </script>

  <!-- Prompt IE 6 users to install Chrome Frame. We suggest that you not support IE 6.
       chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7 ]>
    <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
    <script>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
  <![endif]-->

  <!-- Social Widget Rendering Javascript /-->
  <script src="http://platform.twitter.com/widgets.js"></script>
  <script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script>
  <script type="text/javascript">
    (function() {
      var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
      po.src = 'https://apis.google.com/js/plusone.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
    })();
  </script>
  <!-- End Social Widget Rendering Javascript /-->
</body>
</html>
