<div>
  <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th colspan="5">
            <h2 style="display:inline-block;">Articles</h2>
            <a style="float: right" class="btn btn-large" href="/admin/articles/add"><i class="icon-plus"></i></a>
          </th>
        </tr>
        <tr>
          <th>ID</th>
          <th>Status</th>
          <th>Title</th>
          <th>Categories</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <?php if(count($this->articles)): ?>
          <?php foreach ($this->articles as $article): ?>
          <tr>
            <td width="5%"><?= $article->id; ?></td>
            <td width="6%">
              <span class="label <?= ($article->status) ? "label-success" : ""; ?>">
                <?= ($article->status) ? "Online" : "Offline"; ?>
              </span>
            </td>
            <td width="40%"><a href="/articles/view/<?= $article->id; ?>"><?= $article->title; ?></a></td>
            <td width="20%">
              <?php foreach ($article->categories as $category): ?>
                <a href="/categories/view/<?= $category->id; ?>"><?= $category->name; ?></a>
              <?php endforeach; ?>
            </td>
            <td width="8%">
              <a class="btn btn-primary" href="/admin/articles/edit/<?= $article->id; ?>"><i class="icon-edit icon-white"></i></a>
              <a class="btn btn-danger delete" href="/admin/articles/delete/<?= $article->id; ?>"><i class="icon-trash icon-white"></i></a>
            </td>
          </tr>
          <?php endforeach; ?>
        <?php else: ?>
          <tr>
            <td colspan="5" style="text-align: center;">No articles</td>
          </tr>
        <?php endif; ?>
      </tbody>
    </table>
</div>