<div>
  <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th><h2>Articles</h2></th>
        </tr>
      </thead>
      <tbody>
        <?php if(count($this->articles)): ?>
        <?php foreach ($this->articles as $article): ?>
        <tr>
          <td>
            <h3><a href="/articles/view/<?= $article->id; ?>"><?= $article->title; ?></a></h3>
            <p>
              <?php foreach ($article->categories as $category): ?>
                <a href="/categories/view/<?= $category->id; ?>"><?= $category->name; ?></a>
              <?php endforeach; ?>
            </p>
            <p><?= $article->text; ?></p>
          </td>
        </tr>
        <?php endforeach; ?>
        <?php else: ?>
          <tr>
            <td style="text-align: center;">No articles</td>
          </tr>
        <?php endif; ?>
      </tbody>
    </table>
</div>